services:
  productsv_db:
    image: postgres:16
    environment:
      POSTGRES_DB: book_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - book_service_db_vol:/var/lib/postgresql/data

volumes:
  book_service_db_vol: {}
