services:
  book_service_db:
    image: postgres:16
    environment:
      POSTGRES_DB: book_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - book_service_db_vol:/var/lib/postgresql/data
    networks:
      - kafkanet

  customer_service_db:
    image: postgres:16
    environment:
      POSTGRES_DB: customer_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - customer_service_db_vol:/var/lib/postgresql/data
    networks:
      - kafkanet

  borrow_service_db:
    image: postgres:16
    environment:
      POSTGRES_DB: borrow_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - borrow_service_db_vol:/var/lib/postgresql/data
    networks:
      - kafkanet

  fine_service_db:
    image: postgres:16
    environment:
      POSTGRES_DB: fine_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - fine_service_db_vol:/var/lib/postgresql/data
    networks:
      - kafkanet

  review_service_db:
    image: postgres:16
    environment:
      POSTGRES_DB: review_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - review_service_db_vol:/var/lib/postgresql/data
    networks:
      - kafkanet

  kafka:
    image: apache/kafka:3.8.0
    restart: unless-stopped
    ports:
      - "9092:9092" # container içi (PLAINTEXT) - diğer container'lar için
      - "9094:9094" # host'tan erişim (EXTERNAL)
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
      KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

    volumes:
      - kafka_vol:/var/lib/kafka/data

    networks:
      - kafkanet

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8079:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"

    networks:
      - kafkanet

  config-server:
    build:
      context: ./config-server
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./configurations:/configurations:ro
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/configurations,file:/configurations/{application}
    networks:
      - kafkanet

  discovery-server:
    build:
      context: ./discovery-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
    networks:
      - kafkanet

  gateway-server:
    build:
      context: ./gateway-server
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
    networks:
      - kafkanet

  book-service:
    build:
      context: ./book-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
      - book_service_db
      - kafka
    networks:
      - kafkanet

  customer-service:
    build:
      context: ./customer-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
      - customer_service_db
    networks:
      - kafkanet

  borrow-service:
    build:
      context: ./borrow-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
      - borrow_service_db
      - kafka
    networks:
      - kafkanet

  fine-service:
    build:
      context: ./fine-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
      - fine_service_db
      - kafka
    networks:
      - kafkanet

  review-service:
    build:
      context: ./review-service
    restart: unless-stopped
    ports:
      - "8086:8083"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8787"
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server
      - discovery-server
      - review_service_db
    networks:
      - kafkanet

volumes:
  book_service_db_vol: {}
  customer_service_db_vol: {}
  borrow_service_db_vol: {}
  fine_service_db_vol: {}
  review_service_db_vol: {}
  kafka_vol: {}

networks:
  kafkanet:
