eureka:
  service-url:
    defaultZone: http://discovery-server:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://borrow_service_db:5432/borrow_service_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        kafkaTest-in-0:
          destination: kafka-test-topic
          group: borrow-service
        borrowOverdue-out-0:
          destination: borrow-overdue-events
          contentType: application/json

borrow-service:
  remote-validation:
    enabled: false
  reservation:
    auto-hold-ttl: PT24H

