eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/fine_service_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9094
      bindings:
        borrowOverdue-in-0:
          destination: borrow-overdue-events
          group: fine-service
          contentType: application/json

fine-service:
  remote-validation:
    enabled: false
  overdue:
    rate-per-day: 5.00

