spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:../configurations,file:../configurations/{application}
        git:
          uri: https://github.com/BeytullahCetin/microservice-library-app.git
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}

server:
  port: 8787
